"""
File2Flow — Python Conversion Engine
Professional-grade document-to-PDF conversion engine.
Supports: DOCX, XLSX, CSV, PPTX, JSON, Markdown, HTML, TXT, Images, RTF
"""

import io
import os
import json
import csv
import uuid
import tempfile
from pathlib import Path
from typing import Optional
from dataclasses import dataclass

from reportlab.lib.pagesizes import A4, LETTER, LEGAL
from reportlab.lib.units import mm, inch
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image as RLImage, PageBreak, HRFlowable, KeepTogether
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

from PIL import Image as PILImage


@dataclass
class ConversionOptions:
    page_size: str = "a4"
    orientation: str = "portrait"
    margin: str = "normal"
    watermark: str = ""
    add_page_numbers: bool = True
    quality: str = "high"
    image_fit: str = "contain"


# ============================================================
# PAGE SIZE & MARGIN HELPERS
# ============================================================

def get_page_size(page_size: str, orientation: str):
    sizes = {"a4": A4, "letter": LETTER, "legal": LEGAL}
    ps = sizes.get(page_size, A4)
    if orientation == "landscape":
        return (ps[1], ps[0])
    return ps


def get_margin_mm(margin: str) -> float:
    margins = {"narrow": 12, "normal": 22, "wide": 32, "none": 8}
    return margins.get(margin, 22)


def get_styles():
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name="DocTitle",
        parent=styles["Title"],
        fontSize=24,
        leading=30,
        textColor=HexColor("#0F172A"),
        spaceAfter=12,
        alignment=TA_CENTER,
    ))

    styles.add(ParagraphStyle(
        name="DocSubtitle",
        parent=styles["Normal"],
        fontSize=11,
        leading=14,
        textColor=HexColor("#64748B"),
        alignment=TA_CENTER,
        spaceAfter=20,
    ))

    styles.add(ParagraphStyle(
        name="SectionHeader",
        parent=styles["Heading1"],
        fontSize=16,
        leading=20,
        textColor=HexColor("#1E40AF"),
        spaceBefore=18,
        spaceAfter=8,
        borderWidth=0,
        borderPadding=0,
    ))

    styles.add(ParagraphStyle(
        name="TableHeader",
        parent=styles["Normal"],
        fontSize=9,
        leading=12,
        textColor=white,
        fontName="Helvetica-Bold",
        alignment=TA_LEFT,
    ))

    styles.add(ParagraphStyle(
        name="TableCell",
        parent=styles["Normal"],
        fontSize=9,
        leading=12,
        textColor=HexColor("#1E293B"),
    ))

    styles.add(ParagraphStyle(
        name="TableCellRight",
        parent=styles["Normal"],
        fontSize=9,
        leading=12,
        textColor=HexColor("#1E293B"),
        alignment=TA_RIGHT,
        fontName="Courier",
    ))

    styles.add(ParagraphStyle(
        name="CodeBlock",
        parent=styles["Normal"],
        fontSize=8,
        leading=11,
        textColor=HexColor("#E2E8F0"),
        fontName="Courier",
        backColor=HexColor("#1E293B"),
        borderWidth=0,
        borderPadding=8,
        spaceBefore=8,
        spaceAfter=8,
    ))

    styles.add(ParagraphStyle(
        name="JsonKey",
        parent=styles["Normal"],
        fontSize=9,
        leading=12,
        textColor=HexColor("#2563EB"),
        fontName="Courier-Bold",
    ))

    styles.add(ParagraphStyle(
        name="BodyText2",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        textColor=HexColor("#334155"),
        alignment=TA_JUSTIFY,
    ))

    styles.add(ParagraphStyle(
        name="BulletItem",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        textColor=HexColor("#334155"),
        leftIndent=20,
        bulletIndent=8,
        spaceBefore=2,
        spaceAfter=2,
    ))

    return styles


def build_doc(filename: str, options: ConversionOptions):
    page_size = get_page_size(options.page_size, options.orientation)
    margin_mm = get_margin_mm(options.margin)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=page_size,
        leftMargin=margin_mm * mm,
        rightMargin=margin_mm * mm,
        topMargin=margin_mm * mm,
        bottomMargin=margin_mm * mm,
    )
    return doc, buf, page_size, margin_mm


def add_title(story, name: str, format_label: str, styles):
    story.append(Paragraph(name, styles["DocTitle"]))
    story.append(Paragraph(f"{format_label} &bull; Generated by File2Flow", styles["DocSubtitle"]))
    story.append(HRFlowable(width="40%", thickness=2, color=HexColor("#2563EB"), spaceAfter=16, spaceBefore=4))


def add_watermark(story, watermark: str, page_width, page_height):
    pass


def add_page_number(canvas, doc, total_pages=None):
    page_num = canvas.getPageNumber()
    text = f"Page {page_num}"
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(HexColor("#94A3B8"))
    canvas.drawCentredString(doc.pagesize[0] / 2, 15 * mm, text)
    canvas.restoreState()


def add_watermark_to_canvas(canvas, doc, watermark: str):
    if not watermark:
        return
    canvas.saveState()
    canvas.setFont("Helvetica-Bold", 40)
    canvas.setFillColor(HexColor("#E2E8F0"))
    canvas.translate(doc.pagesize[0] / 2, doc.pagesize[1] / 2)
    canvas.rotate(45)
    canvas.drawCentredString(0, 0, watermark)
    canvas.restoreState()


# ============================================================
# DOCX CONVERSION
# ============================================================

def convert_docx(file_path: str, options: ConversionOptions) -> bytes:
    from docx import Document

    doc = Document(file_path)
    styles = get_styles()
    pdf_doc, buf, page_size, margin_mm = build_doc(
        Path(file_path).stem, options
    )
    story = []

    add_title(story, Path(file_path).stem, "Word Document", styles)

    for para in doc.paragraphs:
        text = para.text.strip()
        if not text:
            story.append(Spacer(1, 6))
            continue

        style_name = para.style.name.lower()

        if "heading 1" in style_name or "title" in style_name:
            story.append(Paragraph(text, styles["SectionHeader"]))
        elif "heading 2" in style_name:
            story.append(Paragraph(text, ParagraphStyle(
                "H2", parent=styles["SectionHeader"], fontSize=13, textColor=HexColor("#2563EB")
            )))
        elif "heading 3" in style_name:
            story.append(Paragraph(text, ParagraphStyle(
                "H3", parent=styles["SectionHeader"], fontSize=11, textColor=HexColor("#1E293B")
            )))
        elif "list" in style_name:
            story.append(Paragraph(f"&bull; {text}", styles["BulletItem"]))
        else:
            # Handle bold runs
            formatted = ""
            for run in para.runs:
                if run.bold:
                    formatted += f"<b>{run.text}</b>"
                elif run.italic:
                    formatted += f"<i>{run.text}</i>"
                else:
                    formatted += run.text
            if formatted:
                story.append(Paragraph(formatted, styles["BodyText2"]))

    # Convert tables
    for table in doc.tables:
        data = []
        for row in table.rows:
            data.append([cell.text for cell in row.cells])

        if data:
            t = Table(data, repeatRows=1)
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), HexColor("#1E293B")),
                ("TEXTCOLOR", (0, 0), (-1, 0), white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
                ("TOPPADDING", (0, 0), (-1, 0), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("BACKGROUND", (0, 1), (-1, -1), HexColor("#F8FAFC")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#F8FAFC"), white]),
                ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]))
            story.append(Spacer(1, 12))
            story.append(t)
            story.append(Spacer(1, 12))

    def on_page(canvas, doc):
        add_watermark_to_canvas(canvas, doc, options.watermark)
        if options.add_page_numbers:
            add_page_number(canvas, doc)

    pdf_doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buf.getvalue()


# ============================================================
# SPREADSHEET (XLSX / CSV) CONVERSION
# ============================================================

def convert_spreadsheet(file_path: str, options: ConversionOptions, is_csv: bool = False) -> bytes:
    import pandas as pd

    if is_csv:
        df = pd.read_csv(file_path)
        sheets = {"Sheet1": df}
    else:
        xls = pd.ExcelFile(file_path)
        sheets = {}
        for name in xls.sheet_names:
            sheets[name] = pd.read_excel(xls, sheet_name=name)

    styles = get_styles()
    pdf_doc, buf, page_size, margin_mm = build_doc(
        Path(file_path).stem, options
    )
    story = []

    label = "CSV Data" if is_csv else "Spreadsheet"
    add_title(story, Path(file_path).stem, label, styles)

    for sheet_name, df in sheets.items():
        if len(sheets) > 1:
            story.append(Paragraph(sheet_name, styles["SectionHeader"]))

        story.append(Paragraph(
            f"{len(df)} rows &times; {len(df.columns)} columns",
            styles["DocSubtitle"]
        ))
        story.append(Spacer(1, 8))

        # Build table data
        headers = [str(c) for c in df.columns.tolist()]
        table_data = [headers]

        for _, row in df.iterrows():
            cells = []
            for val in row:
                if pd.isna(val):
                    cells.append("")
                else:
                    cells.append(str(val))
            table_data.append(cells)

        if table_data:
            col_widths = None
            page_w = page_size[0] - margin_mm * 2 * mm
            num_cols = len(headers)
            if num_cols > 0:
                w = page_w / num_cols
                col_widths = [w] * num_cols

            t = Table(table_data, colWidths=col_widths, repeatRows=1)

            style_cmds = [
                ("BACKGROUND", (0, 0), (-1, 0), HexColor("#1E293B")),
                ("TEXTCOLOR", (0, 0), (-1, 0), white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("FONTSIZE", (0, 1), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
                ("TOPPADDING", (0, 0), (-1, 0), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#F8FAFC"), white]),
                ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]

            t.setStyle(TableStyle(style_cmds))
            story.append(t)
            story.append(Spacer(1, 16))

    def on_page(canvas, doc):
        add_watermark_to_canvas(canvas, doc, options.watermark)
        if options.add_page_numbers:
            add_page_number(canvas, doc)

    pdf_doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buf.getvalue()


# ============================================================
# POWERPOINT CONVERSION
# ============================================================

def convert_pptx(file_path: str, options: ConversionOptions) -> bytes:
    from pptx import Presentation

    prs = Presentation(file_path)
    styles = get_styles()
    pdf_doc, buf, page_size, margin_mm = build_doc(
        Path(file_path).stem, options
    )
    story = []

    add_title(story, Path(file_path).stem, "Presentation", styles)
    story.append(Paragraph(
        f"{len(prs.slides)} slide{'s' if len(prs.slides) != 1 else ''}",
        styles["DocSubtitle"]
    ))

    for i, slide in enumerate(prs.slides):
        story.append(Spacer(1, 12))

        slide_texts = []
        for shape in slide.shapes:
            if shape.has_text_frame:
                for para in shape.text_frame.paragraphs:
                    text = para.text.strip()
                    if text:
                        slide_texts.append(text)

        if not slide_texts:
            continue

        # Slide container
        slide_content = []
        slide_content.append(Paragraph(
            f"SLIDE {i + 1}",
            ParagraphStyle("SlideNum", parent=styles["Normal"], fontSize=8,
                           textColor=HexColor("#2563EB"), fontName="Helvetica-Bold",
                           spaceAfter=6)
        ))

        for j, text in enumerate(slide_texts):
            if j == 0:
                slide_content.append(Paragraph(
                    text, ParagraphStyle("SlideTitle", parent=styles["Normal"],
                                         fontSize=14, leading=18,
                                         textColor=HexColor("#0F172A"),
                                         fontName="Helvetica-Bold",
                                         spaceAfter=6)
                ))
            else:
                slide_content.append(Paragraph(
                    text, ParagraphStyle("SlideBody", parent=styles["Normal"],
                                         fontSize=10, leading=14,
                                         textColor=HexColor("#334155"),
                                         spaceAfter=4)
                ))

        # Wrap in a table for visual box
        inner = []
        for item in slide_content:
            inner.append([item])

        t = Table(inner, colWidths=[page_size[0] - margin_mm * 2 * mm - 16 * mm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), HexColor("#F8FAFC")),
            ("BOX", (0, 0), (-1, -1), 1, HexColor("#E2E8F0")),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("ROUNDEDCORNERS", [6, 6, 6, 6]),
        ]))
        story.append(t)

    def on_page(canvas, doc):
        add_watermark_to_canvas(canvas, doc, options.watermark)
        if options.add_page_numbers:
            add_page_number(canvas, doc)

    pdf_doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buf.getvalue()


# ============================================================
# JSON CONVERSION
# ============================================================

def convert_json(file_path: str, options: ConversionOptions) -> bytes:
    with open(file_path, "r", encoding="utf-8") as f:
        raw = f.read()

    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        data = None

    styles = get_styles()
    pdf_doc, buf, page_size, margin_mm = build_doc(
        Path(file_path).stem, options
    )
    story = []

    add_title(story, Path(file_path).stem, "JSON Data", styles)

    file_size = len(raw.encode("utf-8"))
    if file_size > 1024:
        size_str = f"{file_size / 1024:.1f} KB"
    else:
        size_str = f"{file_size} B"

    if isinstance(data, list):
        story.append(Paragraph(
            f"{len(data)} items &bull; {size_str}",
            styles["DocSubtitle"]
        ))
    elif isinstance(data, dict):
        story.append(Paragraph(
            f"{len(data)} keys &bull; {size_str}",
            styles["DocSubtitle"]
        ))
    else:
        story.append(Paragraph(size_str, styles["DocSubtitle"]))

    story.append(Spacer(1, 12))

    # If array of objects, render as table
    if isinstance(data, list) and len(data) > 0 and isinstance(data[0], dict):
        all_keys = []
        seen = set()
        for item in data:
            for k in item.keys():
                if k not in seen:
                    all_keys.append(k)
                    seen.add(k)

        # Table view
        story.append(Paragraph("Table View", styles["SectionHeader"]))

        headers = all_keys
        table_data = [headers]
        for item in data[:500]:
            row = []
            for k in all_keys:
                val = item.get(k)
                if val is None:
                    row.append("null")
                elif isinstance(val, (dict, list)):
                    s = json.dumps(val, ensure_ascii=False)
                    row.append(s[:60] + "..." if len(s) > 60 else s)
                else:
                    row.append(str(val))
            table_data.append(row)

        page_w = page_size[0] - margin_mm * 2 * mm
        num_cols = len(headers)
        col_w = page_w / max(num_cols, 1)

        t = Table(table_data, colWidths=[col_w] * num_cols, repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#1E293B")),
            ("TEXTCOLOR", (0, 0), (-1, 0), white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 8),
            ("FONTSIZE", (0, 1), (-1, -1), 7),
            ("FONTNAME", (0, 1), (-1, -1), "Courier"),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
            ("TOPPADDING", (0, 0), (-1, 0), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [HexColor("#F8FAFC"), white]),
            ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#E2E8F0")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(t)
        story.append(Spacer(1, 16))

    # Raw JSON view
    story.append(Paragraph("Raw JSON", styles["SectionHeader"]))
    formatted = json.dumps(data, indent=2, ensure_ascii=False) if data else raw

    # Split into chunks for ReportLab
    max_line_len = 90
    lines = formatted.split("\n")
    for line in lines:
        safe = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        if len(safe) > max_line_len:
            safe = safe[:max_line_len] + "..."
        story.append(Paragraph(f"<font face='Courier' size='8'>{safe}</font>", styles["BodyText2"]))

    def on_page(canvas, doc):
        add_watermark_to_canvas(canvas, doc, options.watermark)
        if options.add_page_numbers:
            add_page_number(canvas, doc)

    pdf_doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buf.getvalue()


# ============================================================
# MARKDOWN CONVERSION
# ============================================================

def convert_markdown(file_path: str, options: ConversionOptions) -> bytes:
    import markdown as md

    with open(file_path, "r", encoding="utf-8") as f:
        raw = f.read()

    styles = get_styles()
    pdf_doc, buf, page_size, margin_mm = build_doc(
        Path(file_path).stem, options
    )
    story = []

    add_title(story, Path(file_path).stem, "Markdown", styles)

    # Convert markdown to HTML then parse into ReportLab
    html = md.markdown(raw, extensions=["tables", "fenced_code", "codehilite"])

    # Simple HTML to ReportLab flowables
    from reportlab.platypus import Paragraph as RLPara
    import re

    # Strip HTML tags for simple conversion
    def html_to_flowables(html_content):
        flowables = []
        # Split by block elements
        blocks = re.split(r'\n\s*\n', html_content)
        for block in blocks:
            block = block.strip()
            if not block:
                continue

            # Headers
            h_match = re.match(r'<h(\d)>(.*?)</h\1>', block, re.DOTALL)
            if h_match:
                level = int(h_match.group(1))
                text = re.sub(r'<[^>]+>', '', h_match.group(2))
                if level == 1:
                    flowables.append(Paragraph(text, ParagraphStyle(
                        "MDH1", parent=styles["SectionHeader"], fontSize=18, textColor=HexColor("#0F172A")
                    )))
                elif level == 2:
                    flowables.append(Paragraph(text, ParagraphStyle(
                        "MDH2", parent=styles["SectionHeader"], fontSize=14, textColor=HexColor("#1E40AF")
                    )))
                else:
                    flowables.append(Paragraph(text, ParagraphStyle(
                        "MDH3", parent=styles["SectionHeader"], fontSize=12, textColor=HexColor("#334155")
                    )))
                flowables.append(Spacer(1, 6))
                continue

            # Lists
            if block.startswith("<ul") or block.startswith("<ol"):
                items = re.findall(r'<li>(.*?)</li>', block, re.DOTALL)
                for item in items:
                    text = re.sub(r'<[^>]+>', '', item).strip()
                    flowables.append(Paragraph(
                        f"&bull; {text}", styles["BulletItem"]
                    ))
                flowables.append(Spacer(1, 6))
                continue

            # Code blocks
            if block.startswith("<pre") or block.startswith("<code"):
                code = re.sub(r'<[^>]+>', '', block).strip()
                flowables.append(Paragraph(
                    code.replace("\n", "<br/>").replace(" ", "&nbsp;"),
                    styles["CodeBlock"]
                ))
                continue

            # Paragraph
            text = re.sub(r'<[^>]+>', '', block).strip()
            if text:
                # Handle inline bold/italic
                text_html = block
                text_html = re.sub(r'<strong>(.*?)</strong>', r'<b>\1</b>', text_html)
                text_html = re.sub(r'<em>(.*?)</em>', r'<i>\1</i>', text_html)
                # Strip remaining tags
                text_clean = re.sub(r'<[^>]+>', '', text_html).strip()
                if text_clean:
                    flowables.append(Paragraph(text_clean, styles["BodyText2"]))
                    flowables.append(Spacer(1, 4))

        return flowables

    story.extend(html_to_flowables(html))

    def on_page(canvas, doc):
        add_watermark_to_canvas(canvas, doc, options.watermark)
        if options.add_page_numbers:
            add_page_number(canvas, doc)

    pdf_doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buf.getvalue()


# ============================================================
# HTML CONVERSION
# ============================================================

def convert_html(file_path: str, options: ConversionOptions) -> bytes:
    try:
        from weasyprint import HTML
        page_size = get_page_size(options.page_size, options.orientation)
        margin_mm = get_margin_mm(options.margin)

        html = HTML(filename=file_path)
        pdf_bytes = html.write_pdf()
        return pdf_bytes
    except Exception:
        # Fallback: plain text extraction
        with open(file_path, "r", encoding="utf-8") as f:
            raw = f.read()
        import re
        text = re.sub(r'<[^>]+>', '\n', raw)
        text = re.sub(r'\n{3,}', '\n\n', text).strip()

        tmp = tempfile.NamedTemporaryFile(suffix=".txt", delete=False, mode="w", encoding="utf-8")
        tmp.write(text)
        tmp.close()
        try:
            return convert_text(tmp.name, options)
        finally:
            os.unlink(tmp.name)


# ============================================================
# PLAIN TEXT CONVERSION
# ============================================================

def convert_text(file_path: str, options: ConversionOptions) -> bytes:
    with open(file_path, "r", encoding="utf-8", errors="replace") as f:
        raw = f.read()

    styles = get_styles()
    pdf_doc, buf, page_size, margin_mm = build_doc(
        Path(file_path).stem, options
    )
    story = []

    add_title(story, Path(file_path).stem, "Text Document", styles)

    for para in raw.split("\n\n"):
        para = para.strip()
        if para:
            safe = para.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            safe = safe.replace("\n", "<br/>")
            story.append(Paragraph(safe, styles["BodyText2"]))
            story.append(Spacer(1, 6))

    def on_page(canvas, doc):
        add_watermark_to_canvas(canvas, doc, options.watermark)
        if options.add_page_numbers:
            add_page_number(canvas, doc)

    pdf_doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buf.getvalue()


# ============================================================
# IMAGE CONVERSION
# ============================================================

def convert_image(file_path: str, options: ConversionOptions) -> bytes:
    img = PILImage.open(file_path)
    img_width, img_height = img.size

    page_size = get_page_size(options.page_size, options.orientation)
    margin_mm = get_margin_mm(options.margin)

    page_w = page_size[0] - margin_mm * 2 * mm
    page_h = page_size[1] - margin_mm * 2 * mm

    # Fit image to page
    if options.image_fit == "contain":
        ratio = min(page_w / (img_width * 0.75), page_h / (img_height * 0.75))
        display_w = img_width * 0.75 * ratio
        display_h = img_height * 0.75 * ratio
    elif options.image_fit == "cover":
        ratio = max(page_w / (img_width * 0.75), page_h / (img_height * 0.75))
        display_w = img_width * 0.75 * ratio
        display_h = img_height * 0.75 * ratio
    else:
        display_w = min(img_width * 0.75, page_w)
        display_h = min(img_height * 0.75, page_h)

    styles = get_styles()
    pdf_doc, buf, _, _ = build_doc(Path(file_path).stem, options)
    story = []

    add_title(story, Path(file_path).stem, "Image", styles)

    # Save temp image for ReportLab (must exist until build completes)
    tmp_path = os.path.join(tempfile.gettempdir(), f"f2f_img_{uuid.uuid4().hex}{Path(file_path).suffix}")
    img.save(tmp_path)
    rl_img = RLImage(tmp_path, width=display_w, height=display_h)
    story.append(rl_img)
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        f"{img.size[0]} &times; {img.size[1]} px &bull; {Path(file_path).suffix.upper()[1:]}",
        styles["DocSubtitle"]
    ))

    def on_page(canvas, doc):
        add_watermark_to_canvas(canvas, doc, options.watermark)
        if options.add_page_numbers:
            add_page_number(canvas, doc)

    pdf_doc.build(story, onFirstPage=on_page, onLaterPages=on_page)

    if os.path.exists(tmp_path):
        os.unlink(tmp_path)

    return buf.getvalue()


# ============================================================
# MAIN CONVERTER FUNCTION
# ============================================================

def convert_to_pdf(file_path: str, options: Optional[ConversionOptions] = None) -> bytes:
    if options is None:
        options = ConversionOptions()

    ext = Path(file_path).suffix.lower()

    converters = {
        ".docx": lambda: convert_docx(file_path, options),
        ".doc": lambda: convert_docx(file_path, options),
        ".xlsx": lambda: convert_spreadsheet(file_path, options, is_csv=False),
        ".xls": lambda: convert_spreadsheet(file_path, options, is_csv=False),
        ".csv": lambda: convert_spreadsheet(file_path, options, is_csv=True),
        ".pptx": lambda: convert_pptx(file_path, options),
        ".ppt": lambda: convert_pptx(file_path, options),
        ".json": lambda: convert_json(file_path, options),
        ".md": lambda: convert_markdown(file_path, options),
        ".markdown": lambda: convert_markdown(file_path, options),
        ".html": lambda: convert_html(file_path, options),
        ".htm": lambda: convert_html(file_path, options),
        ".txt": lambda: convert_text(file_path, options),
        ".rtf": lambda: convert_text(file_path, options),
        ".png": lambda: convert_image(file_path, options),
        ".jpg": lambda: convert_image(file_path, options),
        ".jpeg": lambda: convert_image(file_path, options),
        ".webp": lambda: convert_image(file_path, options),
        ".gif": lambda: convert_image(file_path, options),
        ".bmp": lambda: convert_image(file_path, options),
        ".svg": lambda: convert_text(file_path, options),
    }

    converter = converters.get(ext)
    if converter is None:
        raise ValueError(f"Unsupported format: {ext}")

    return converter()
