"""
File2Flow — Engine Test Suite
Tests all conversion formats against the Python engine.
"""

import os
import sys
import json
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from converter import convert_to_pdf, ConversionOptions

# ============================================================
# TEST FILE GENERATORS
# ============================================================

def create_test_docx(path):
    from docx import Document
    doc = Document()
    doc.add_heading("File2Flow Test Document", 0)
    doc.add_paragraph("This is a test Word document for PDF conversion.")
    doc.add_heading("Features", 1)
    doc.add_paragraph("Supports headings, paragraphs, tables, and lists.")
    doc.add_heading("Table Test", 2)
    table = doc.add_table(rows=3, cols=3)
    table.style = "Table Grid"
    for i, row in enumerate(table.rows):
        for j, cell in enumerate(row.cells):
            cell.text = f"Cell {i},{j}"
    doc.add_paragraph("")
    doc.add_paragraph("Bold text test:", style="List Bullet")
    doc.save(path)


def create_test_xlsx(path):
    import openpyxl
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Revenue"
    ws.append(["Quarter", "Revenue", "Expenses", "Profit"])
    ws.append(["Q1 2026", 1450000, 920000, 530000])
    ws.append(["Q2 2026", 1820000, 1050000, 770000])
    ws.append(["Q3 2026", 2290000, 1180000, 1110000])
    ws.append(["Q4 2026", 2500000, 1300000, 1200000])
    ws2 = wb.create_sheet("Summary")
    ws2.append(["Metric", "Value"])
    ws2.append(["Total Revenue", 8060000])
    ws2.append(["Total Profit", 3610000])
    wb.save(path)


def create_test_csv(path):
    import csv
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Name", "Email", "Role", "Department"])
        w.writerow(["Alice Johnson", "alice@test.com", "Engineer", "Engineering"])
        w.writerow(["Bob Smith", "bob@test.com", "Designer", "Design"])
        w.writerow(["Carol White", "carol@test.com", "Manager", "Product"])
        w.writerow(["Dave Brown", "dave@test.com", "Analyst", "Data"])


def create_test_pptx(path):
    from pptx import Presentation
    prs = Presentation()
    slide1 = prs.slides.add_slide(prs.slide_layouts[0])
    slide1.shapes.title.text = "File2Flow Presentation"
    slide1.placeholders[1].text = "PDF Conversion Engine Test"
    slide2 = prs.slides.add_slide(prs.slide_layouts[1])
    slide2.shapes.title.text = "Key Features"
    body = slide2.placeholders[1]
    body.text = "Multi-format support\nHigh fidelity output\nBatch processing"
    slide3 = prs.slides.add_slide(prs.slide_layouts[1])
    slide3.shapes.title.text = "Architecture"
    body = slide3.placeholders[1]
    body.text = "React frontend\nPython engine\nFastAPI server"
    prs.save(path)


def create_test_json(path):
    data = {
        "company": "File2Flow",
        "version": "1.0.0",
        "features": ["PDF Conversion", "Batch Processing", "AI Enhancement"],
        "team": [
            {"name": "Alice", "role": "Lead Engineer", "active": True},
            {"name": "Bob", "role": "Designer", "active": True},
            {"name": "Carol", "role": "Product Manager", "active": False},
        ],
        "stats": {
            "total_conversions": 15420,
            "success_rate": 0.997,
            "avg_time_ms": 1200
        }
    }
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


def create_test_markdown(path):
    content = """# File2Flow — Markdown Test

## Overview

This document tests **Markdown to PDF** conversion with the Python engine.

### Features Supported

- **Bold text** and *italic text*
- Headers (H1, H2, H3)
- Lists (bullet and numbered)
- Code blocks
- Links and emphasis

## Code Example

```python
def hello():
    print("Hello from File2Flow!")
```

## Table

| Feature | Status | Priority |
|---------|--------|----------|
| DOCX | Done | High |
| XLSX | Done | High |
| PPTX | Done | Medium |
| JSON | Done | Medium |

---

*Generated by File2Flow Python Engine*
"""
    with open(path, "w") as f:
        f.write(content)


def create_test_html(path):
    html = """<!DOCTYPE html>
<html>
<head><title>File2Flow HTML Test</title></head>
<body>
<h1>HTML to PDF Test</h1>
<p>This is a <strong>test HTML page</strong> for conversion to PDF.</p>
<table border="1" cellpadding="8">
<tr><th>Name</th><th>Score</th></tr>
<tr><td>Alice</td><td>95</td></tr>
<tr><td>Bob</td><td>87</td></tr>
</table>
<ul>
<li>Item 1</li>
<li>Item 2</li>
<li>Item 3</li>
</ul>
</body>
</html>"""
    with open(path, "w") as f:
        f.write(html)


def create_test_text(path):
    content = """File2Flow Plain Text Test
========================

This is a plain text file being converted to PDF.

Features:
- Automatic text wrapping
- Clean typography
- Professional formatting

The quick brown fox jumps over the lazy dog.
Pack my box with five dozen liquor jugs.
"""
    with open(path, "w") as f:
        f.write(content)


def create_test_image(path):
    from PIL import Image, ImageDraw
    img = Image.new("RGB", (800, 600), color="#2563EB")
    draw = ImageDraw.Draw(img)
    draw.rectangle([50, 50, 750, 550], fill="#EFF6FF", outline="#1E40AF", width=3)
    draw.text((300, 280), "File2Flow", fill="#0F172A")
    img.save(path)


# ============================================================
# TEST RUNNER
# ============================================================

def run_tests():
    test_dir = Path(tempfile.mkdtemp(prefix="file2flow_test_"))
    results = []

    tests = [
        ("DOCX to PDF", "docx", create_test_docx),
        ("XLSX to PDF", "xlsx", create_test_xlsx),
        ("CSV to PDF", "csv", create_test_csv),
        ("PPTX to PDF", "pptx", create_test_pptx),
        ("JSON to PDF", "json", create_test_json),
        ("Markdown to PDF", "md", create_test_markdown),
        ("HTML to PDF", "html", create_test_html),
        ("TXT to PDF", "txt", create_test_text),
        ("PNG to PDF", "png", create_test_image),
        ("JPG to PDF", "jpg", create_test_image),
    ]

    options = ConversionOptions(
        page_size="a4",
        orientation="portrait",
        margin="normal",
        watermark="DRAFT",
        add_page_numbers=True,
    )

    print("=" * 60)
    print("File2Flow — Python Engine Test Suite")
    print("=" * 60)
    print()

    for name, ext, creator in tests:
        input_path = str(test_dir / f"test.{ext}")
        try:
            creator(input_path)
            pdf_bytes = convert_to_pdf(input_path, options)
            size_kb = len(pdf_bytes) / 1024
            print(f"  PASS  {name:25s}  {size_kb:8.1f} KB")
            results.append((name, True, size_kb))
        except Exception as e:
            print(f"  FAIL  {name:25s}  {str(e)[:50]}")
            results.append((name, False, 0))

    print()
    print("-" * 60)
    passed = sum(1 for _, ok, _ in results if ok)
    total = len(results)
    print(f"Results: {passed}/{total} passed")
    print("-" * 60)

    # Cleanup
    import shutil
    shutil.rmtree(test_dir, ignore_errors=True)

    return passed == total


if __name__ == "__main__":
    success = run_tests()
    sys.exit(0 if success else 1)
